---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: text
  name: summary
  label: summary
- type: list
  name: authors
  label: authors
  config:
    min: '1'
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: datetime
  name: date
  label: date
  config:
    required: true
  default: now
- type: text
  name: external_link
  label: external_link
- type: field_group
  name: image
  label: image
  fields:
  - type: text
    name: caption
    label: caption
  - type: text
    name: focal_point
    label: focal_point
  - type: boolean
    name: preview_only
    label: preview_only
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
- type: text
  name: url_code
  label: url_code
- type: text
  name: url_pdf
  label: url_pdf
- type: text
  name: url_slides
  label: url_slides
- type: text
  name: url_video
  label: url_video
- type: text
  name: slides
  label: slides
